### PR TITLE
OPManager: fix preview

### PR DESCRIPTION
**Pull request by izotomas**
add '--in-file' cli parameter when building command line

the issue is described in #8

### CODE REVIEW

**Comment by shyim** [comment]
Thanks!

**Comment by izotomas** [comment]
you're welcome! 
I see the plugin wasn't published (due to some changelog formatting issue) yet, will you have time to fix that?

**Comment by shyim** [comment]
sure. I am on it

**Comment by shyim** [comment]
image
is in review. should be today or tomorrow live

**Pull request merged**
